### ISSUE TITLE
Proposal: Add a dag_only parameter

### ISSUE THREAD

**Issue by gasci** [astronomer/deploy-action#64]
We would like to overwrite the dag_only detection on demand. Therefore, it would be great to have a dag_only parameter.

We want to run the deploy action with the dag_only option even though we change files at a non-dags folder. Currently, we are not able to prevent the full environment build image upload.

**Comment by sunkickr** [comment]
good idea

**Comment by gasci** [comment]
Thank you for the feedback. And is it possible to release a v5 after these additions?

**Comment by gasci** [comment]
Has there been any update on this feature? This feature is really crucial for our pipelines not to push the same image multiple times.

**Comment by neel-astro** [comment]
This is resolved as part of adding dbt deploy support in deploy-action, as we introduced a new `deploy-type` field, that allows users to configure a `dags-only` deploy if the trigger event only had file changes in the `dags` folder.
Reference PR that solves the issue: #74

**Comment by gasci** [comment]
Does it forcefully dag-only deploy even though the file changes say otherwise?

**Comment by neel-astro** [comment]
yeah, so if the deploy-action is configured with `deploy-type` set as `dags-only` then it will have the following behavior:
- When a file is updated inside the `dags` folder - deploy-action would do a dag-only deploy
- When a non-dag file (i.e. file outside the dags folder) is updated - deploy-action will skip any form of deploy since it is configured for dag-only deploy, and in this case, there are no updates in the dags folder
